//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciPortalApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferedCourses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OfferedCourses()
        {
            this.StudentCourses = new HashSet<StudentCourses>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid CourseId { get; set; }
        public System.Guid SemesterId { get; set; }
        public System.Guid TeacherId { get; set; }
        public int Quota { get; set; }
        public int DayOfWeek { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public string DeletedBy { get; set; }
        public int CurrentUserCount { get; set; }
        public int CourseYear { get; set; }
        public string Classroom { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual Semesters Semesters { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentCourses> StudentCourses { get; set; }
    }
}
