//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using OgrenciPortali.Models;

namespace OgrenciPortalApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCourses
    {
        public System.Guid StudentId { get; set; }
        public System.Guid OfferedCourseId { get; set; }
        public int ApprovalStatus { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public string DeletedBy { get; set; }
    
        public virtual OfferedCourses OfferedCourses { get; set; }
        public virtual Users Users { get; set; }
    }
}
