// <auto-generated />
namespace OgrenciPortali.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class ReacreatewithGuidandactivitytracking : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReacreatewithGuidandactivitytracking));
        
        string IMigrationMetadata.Id
        {
            get { return "202507281750486_Reacreate with Guid and activity tracking"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
